'use client';
import styled from 'styled-components';
import Image from 'next/image'; // Import the Image component

export default function About() {
  const skills = [
    'Java',
    'Spring Boot',
    'React.js',
    'Node.js',
    'TypeScript',
    'AWS',
    'Docker',
    'Kubernetes',
  ];

  return (
    <AboutSection id="about">
      <SectionHeading>About Me</SectionHeading>
      <ContentWrapper>
        <div className="about-text">
          <p>
            Hi! I&apos;m Pramodh, a Software Engineer with over 5 years of experience
            building scalable, secure, and cloud-native systems for the web. I&apos;ve
            worked across banking, e-commerce, and healthcare to deliver
            high-performance enterprise applications.
          </p>
          <p>
            I specialize in microservices architecture and cloud platforms like Azure,
            AWS, and GCP—using frameworks such as Spring Boot, React.js, and Node.js
            to create modern, efficient solutions. I&apos;m passionate about writing
            clean, reliable code and automating deployments with Docker, Kubernetes,
            and Terraform.
          </p>
          <p>
            Currently, I&apos;m designing cloud-native banking platforms at Bank of
            America to deliver seamless and secure digital experiences.
          </p>
          <p>Here are a few technologies I&apos;ve been working with recently:</p>
          <SkillsList>
            {skills.map((skill, i) => (
              <li key={i}>{skill}</li>
            ))}
          </SkillsList>
        </div>
        <div className="about-image">
          <div className="image-wrapper">
            <Image
              src="/profile.jpeg" // Path to your image in the public folder
              alt="Pramodh Kamineni"
              width={300} // Set appropriate width
              height={300} // Set appropriate height for a square crop or adjust as needed
              style={{ borderRadius: '4px', objectFit: 'cover', width: '100%', height: '100%' }}
            />
          </div>
        </div>
      </ContentWrapper>
    </AboutSection>
  );
}

/* ---------- Styled Components ---------- */
const AboutSection = styled.section`
  max-width: 900px;
`;

const SectionHeading = styled.h2`
  display: flex;
  align-items: center;
  font-size: 32px;
  font-weight: 600;
  color: ${({ theme }) => theme.colors.lightestSlate};
  margin-bottom: 40px;
  width: 100%;

  &::before {
    content: '01.';
    color: ${({ theme }) => theme.colors.green};
    font-family: ${({ theme }) => theme.fonts.mono};
    font-size: 20px;
    margin-right: 10px;
    font-weight: 400;
  }

  &::after {
    content: '';
    display: block;
    height: 1px;
    width: 300px;
    background-color: ${({ theme }) => theme.colors.lightestNavy};
    margin-left: 20px;
  }

  @media (max-width: 1080px) {
    &::after {
      width: 200px;
    }
  }
  @media (max-width: 768px) {
    &::after {
      width: 100%;
    }
  }
`;

const ContentWrapper = styled.div`
  display: grid;
  grid-template-columns: 3fr 2fr;
  gap: 50px;

  @media (max-width: 768px) {
    display: block;
  }

  .about-text {
    color: ${({ theme }) => theme.colors.slate};
    font-size: 18px;
    line-height: 1.5;

    p {
      margin-bottom: 15px;
    }
  }

  .about-image {
    position: relative;
    max-width: 300px; /* Adjust as needed */

    @media (max-width: 768px) {
      margin: 50px auto;
    }

    .image-wrapper {
      display: block;
      position: relative;
      width: 100%;
      border-radius: 4px;
      background-color: ${({ theme }) => theme.colors.green}; /* Border color */

      &:hover,
      &:focus {
        transform: translate(-4px, -4px);
      }

      &::after {
        content: '';
        display: block;
        position: absolute;
        top: 14px;
        left: 14px;
        width: 100%;
        height: 100%;
        border: 2px solid ${({ theme }) => theme.colors.green};
        border-radius: 4px;
        z-index: -1;
        transition: all 0.25s ease-out;
      }
      &:hover::after {
        top: 10px;
        left: 10px;
      }

      /* Adjust the Image component's parent for aspect ratio if needed */
      & > span { /* Target the wrapper div generated by next/image */
        border-radius: 4px;
      }
    }
  }
`;

const SkillsList = styled.ul`
  display: grid;
  grid-template-columns: repeat(2, minmax(140px, 200px));
  gap: 0 10px;
  padding: 0;
  margin: 20px 0 0 0;
  list-style: none;
  font-family: ${({ theme }) => theme.fonts.mono};
  font-size: 14px;
  color: ${({ theme }) => theme.colors.slate};

  li {
    position: relative;
    margin-bottom: 10px;
    padding-left: 20px;

    &::before {
      content: '▹';
      position: absolute;
      left: 0;
      color: ${({ theme }) => theme.colors.green};
      line-height: 1;
    }
  }
`;
